### ISSUE TITLE
useless coordinates when tesla triggered

### ISSUE THREAD

**Issue by honksJr** [VultraDevs/RavenWatchBugsAndMore#6]
`
gringlegorps - (76561198029074588@steam) triggered the telsa at Gate - **((0.0, 0.0, 0.0))**.
gringlegorps - (76561198029074588@steam) triggered the telsa at Gate - **((0.0, 0.0, 0.0))**.
gringlegorps - (76561198029074588@steam) triggered the telsa at Gate - **((0.0, 0.0, 0.0))**.
gringlegorps - (76561198029074588@steam) triggered the telsa at Gate - **((0.0, 0.0, 0.0))**.
gringlegorps - (76561198029074588@steam) triggered the telsa at Gate - **((0.0, 0.0, 0.0))**.
`

**Comment by VultraDevs** [comment]
Am prob going to remove the coordinates soon or try to actually have the good coordinates. DO NOT FEAR MY honcc. But it may be a issue with SCP SL itself so we'll see.

**Comment by VultraDevs** [comment]
Issue fixed in newest update v0.0.22.0

**Comment by VultraDevs** [comment]
fixed
